import json
import re
import os
import base64
from typing import Optional

def _get_cookie_file(cookie_str: str) -> Optional[str]:
    if not cookie_str:
        return None

    cookie_str = cookie_str.strip().strip('"').strip("'").strip()

    try:
        content = ""
        if cookie_str.startswith('base64:'):
            b64_data = cookie_str[7:].replace(" ", "").replace("\n", "").replace("\r", "")
            raw_bytes = base64.b64decode(b64_data)
            content = raw_bytes.decode('utf-8')
        else:
            clean_str = cookie_str.replace('\n', '').replace('\r', '').replace(' ', '')
            if re.match(r'^[A-Za-z0-9+/=]+$', clean_str):
                try:
                    content = base64.b64decode(clean_str).decode('utf-8')
                except:
                    content = cookie_str
            else:
                content = cookie_str

        print(f"DEBUG: content length before JSON check: {len(content)}")
        print(f"DEBUG: content starts with: {content[:10]!r}")

        if content.strip().startswith('['):
            try:
                cookies = json.loads(content)
                netscape_lines = ["# Netscape HTTP Cookie File", "# Auto-generated from JSON", ""]
                for cookie in cookies:
                    domain = cookie.get('domain', '.youtube.com')
                    c_path = cookie.get('path', '/')
                    secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
                    expires = str(int(cookie.get('expirationDate', 0))) if cookie.get('expirationDate') else '0'
                    name = cookie.get('name', '')
                    value = cookie.get('value', '')
                    if name and value:
                        include_sub = 'TRUE' if domain.startswith('.') else 'FALSE'
                        line = f"{domain}\t{include_sub}\t{c_path}\t{secure}\t{expires}\t{name}\t{value}"
                        netscape_lines.append(line)
                content = "\n".join(netscape_lines)
                print(f"DEBUG: Parsed JSON, content length now: {len(content)}")
            except Exception as je:
                print(f"DEBUG: Failed to parse JSON: {je}")

        if content and "# Netscape" not in content and "# HTTP Cookie File" not in content:
            if ";" in content and "=" in content:
                netscape_lines = ["# Netscape HTTP Cookie File", "# This was auto-generated by SmartLMS", ""]
                for part in content.split(";"):
                    if "=" in part:
                        try:
                            k_v = part.strip().split("=", 1)
                            if len(k_v) == 2:
                                k, v = k_v
                                netscape_lines.append(f".youtube.com\tTRUE\t/\tTRUE\t0\t{k}\t{v}")
                        except: continue
                content = "\n".join(netscape_lines)

        print(f"DEBUG: Checking Netscape/youtube.com headers...")
        if not content or ("# Netscape" not in content and "youtube.com" not in content):
            print(f"DEBUG: Validation failed! content length: {len(content)}")
            return None

        # Sanitize
        valid_lines = []
        for line in content.splitlines():
            if not line.strip() or line.startswith('#'):
                valid_lines.append(line)
                continue
            parts = line.split('\t')
            if len(parts) < 7 and ' ' in line:
                parts = re.split(r'\s+', line.strip(), maxsplit=6)
            
            if len(parts) >= 7:
                try:
                    if parts[4]: float(parts[4])
                    valid_lines.append('\t'.join(parts[:7]))
                except ValueError:
                    parts[4] = '0'
                    valid_lines.append("\t".join(parts[:7]))
        
        content = "\n".join(valid_lines)
        print(f"DEBUG: Final content length after sanitize: {len(content)}")
        return "fake_path.txt"

    except Exception as e:
        print(f"DEBUG: Critical error: {e}")
        return None

# Load the user's file
with open(r'c:\Users\revan\Downloads\www.youtube.com_json_1776503408872.json', 'r', encoding='utf-8') as f:
    test_str = f.read()

result = _get_cookie_file(test_str)
print(f"RESULT: {result}")
